package ims.vi.common.service.client.enums;

public enum MovieHouseResponseCode {
	UNEXPECTED_PRICE_LIST("UNEXPECTED_PRICE_LIST"),
	LOCK_FLAGS_STALED("LOCK_FLAGS_STALED"),
	PURCHASE_TYPE_EXPIRED("PURCHASE_TYPE_EXPIRED"),
	TITLE_PRICE_STALED("TITLE_PRICE_STALED"),
	PRICE_COMBINATION_NOT_FOUND("PRICE_COMBINATION_NOT_FOUND"),
	CASH_POINT_NOT_ENOUGH("CASH_POINT_NOT_ENOUGH"),
	FREE_VIEWABLE_PERIOD("FREE_VIEWABLE_PERIOD"),
	CASH_POINT_BALANCE_STALED("CASH_POINT_BALANCE_STALED"),
	ACCOUNT_NOT_ACTIVE("ACCOUNT_NOT_ACTIVE"),
	ACCOUNT_NOT_FOUND("ACCOUNT_NOT_FOUND"),
	ALREADY_PURCHASED_ONLY_SINGLE_FORMAT("ALREADY_PURCHASED_ONLY_SINGLE_FORMAT"),
	ALREADY_PURCHASED_ONE_OF_TWO_FORMAT("ALREADY_PURCHASED_ONE_OF_TWO_FORMAT"),
	ALREADY_PURCHASED_BOTH_FORMAT("ALREADY_PURCHASED_BOTH_FORMAT"),
	ARMADA_FAIL("ARMADA_FAIL"),
	ASSET_NOT_FOUND("ASSET_NOT_FOUND"),
	EMPTY_RTSP_LINK("EMPTY_RTSP_LINK"),
	EXTERNAL_CALL_ERROR("EXTERNAL_CALL_ERROR"),
	INTERNAL_ERROR("INTERNAL_ERROR"),
	INVALID_INPUT("INVALID_INPUT"),
	INVALID_PROFILE("INVALID_PROFILE"),
	INVALID_SERVICETYPE("INVALID_SERVICETYPE"),
	NEED_TO_UNLOCK("NEED_TO_UNLOCK"),
	PERMIT_EXPIRED("PERMIT_EXPIRED"),
	PPV_BUYTHRU_FAILED("PPV_BUYTHRU_FAILED"),
	PRICE_EXPIRED("PRICE_EXPIRED"),
	PRODUCT_OFFAIR("PRODUCT_OFFAIR"),
	PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND"),
	PURCHASE_FAIL("PURCHASE_FAIL"),
	PURCHASED_OTHER_FORMAT("PURCHASED_OTHER_FORMAT"),
	RESTRICTED_ADULT_CONTENT("RESTRICTED_ADULT_CONTENT"),
	SDX_FAIL("SDX_FAIL"),
	SD_PROFILE_PLAY_HD("SD_PROFILE_PLAY_HD"),
	SUCCESS("SUCCESS"),
	
	//For MH2B
	PURCHASE_ON_OTHER_MACHINE("PURCHASE_ON_OTHER_MACHINE"),
	FSA_STALED("FSA_STALED");
	
	private String code;
	
	MovieHouseResponseCode() {
		this.code = "SUCCESS";
	}
	
	MovieHouseResponseCode(String code) {
		this.code = code;
	}
	
	public String getCode(){
		return this.code;
	}
}
